services:
  nginx:
    container_name: nginx
    image: nginx
    pull_policy: never
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
  
  mariadb:
    container_name: mariadb
    image: mariadb
    pull_policy: never
    build: requirements/mariadb
    restart: always
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
    env_file: .env

  # wordpress:
  #   container_name: wordpress
  #   image: wordpress
  #   pull_policy: never
  #   build: requirements/wordpress
  #   restart: always
  #   networks:
  #     - inception
  #   volumes:
  #     - wordpress:/var/www/wordpress
  #   env_file: .env

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind