services:
  nginx:
    container_name: nginx
    image: nginx
    pull_policy: never
    build:
      context: requirements/nginx
      secrets:
        - inception_secrets
    restart: always
    networks:
      inception:
        # ipv4_address: 172.20.0.3
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
  
  mariadb:
    container_name: mariadb
    image: mariadb
    pull_policy: never
    build:
      context: requirements/mariadb
      secrets:
        - inception_secrets
    restart: always
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    pull_policy: never
    build:
      context: requirements/wordpress
      secrets:
        - inception_secrets
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb

  # firefox:
  #   container_name: firefox
  #   image: jlesage/firefox
  #   networks:
  #     - inception
  #   ports:
  #     - 5800:5800
  #   extra_hosts:
  #     - tchoquet.42.fr:172.20.0.3
    
networks:
  inception:
    name: inception
    # ipam:
    #   config:
    #     - subnet: 172.20.0.0/24

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind

secrets:
  inception_secrets:
    file: .env