services:
  nginx:
    container_name: nginx
    image: nginx
    pull_policy: never
    build:
      context: requirements/nginx
      secrets:
        - inception_secrets
    restart: always
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress
  
  mariadb:
    container_name: mariadb
    image: mariadb
    pull_policy: never
    build:
      context: requirements/mariadb
      secrets:
        - inception_secrets
    restart: always
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    pull_policy: never
    build:
      context: requirements/wordpress
      secrets:
        - inception_secrets
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
  
networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress
      o: bind
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind

secrets:
  inception_secrets:
    file: .env